apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app-deployment
  namespace: portfolio-app
  labels:
    app: portfolio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: ozirichigozie/portfolio:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: portfolio-app
spec:
# Service's <selector> must match Deployment's <labels>
  selector:
    app: portfolio
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      # Service's <targetPort> has to match Deployment's <containerPort>
      targetPort: 80
      nodePort: 31000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: portfolio-app
spec:
  rules:
  - host: portfolio.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-service
            port:
              number: 80
